[project]
name = "modal-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.43.19",
    "fastapi[standard]>=0.136.3",
    "modal>=1.4.3",
    "onnxruntime-gpu>=1.26.0",
    "rembg[gpu]>=2.0.75",
    "requests>=2.34.2",
]
